name: Build and Push Docker Image

on:
  push:
    branches:
      - '**'

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare image tags
        id: meta
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          BRANCH="${GITHUB_REF_NAME}"
          SHA="${GITHUB_SHA::7}"

          BRANCH_TAG=$(echo "$BRANCH" \
            | tr '[:upper:]' '[:lower:]' \
            | sed 's#[^a-z0-9_.-]#-#g')

          IMAGE="ghcr.io/${OWNER}/landing-page"

          echo "image=$IMAGE" >> "$GITHUB_OUTPUT"
          echo "branch_tag=$BRANCH_TAG" >> "$GITHUB_OUTPUT"
          echo "sha_tag=$BRANCH_TAG-$SHA" >> "$GITHUB_OUTPUT"

      - name: Build Docker image
        run: |
          docker build \
            -t "${{ steps.meta.outputs.image }}:${{ steps.meta.outputs.branch_tag }}" \
            -t "${{ steps.meta.outputs.image }}:${{ steps.meta.outputs.sha_tag }}" \
            .

      - name: Push Docker images
        run: |
          docker push "${{ steps.meta.outputs.image }}:${{ steps.meta.outputs.branch_tag }}"
          docker push "${{ steps.meta.outputs.image }}:${{ steps.meta.outputs.sha_tag }}"
      - name: Checkout GitOps repository
        uses: actions/checkout@v4
        with:
          repository: Swe-HimelRana/test-gitops-helm
          token: ${{ secrets.GITOPS_TOKEN }}
          path: gitops
      
      - name: Update Helm image tag
        working-directory: gitops
        run: |
          TAG="${{ steps.meta.outputs.sha_tag }}"
      
          sed -i "s/^  tag:.*/  tag: ${TAG}/" helm/values.yml
      
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      
          git add helm/values.yml
          git commit -m "Update landing-page image to ${TAG}"
          git push
